# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
